### ISSUE TITLE
Try also building using the Magefile in Travis

### ISSUE THREAD

**Issue by frou** [frou/yt2pod#12]
Probably want something like this:

```yaml
before_install:
  - go get    github.com/magefile/mage/...
  - go get -d github.com/frou/yt2pod  # TODO(DH): Can the repo URL come from an env var?
install:
  - mage
```

https://docs.travis-ci.com/user/languages/go/
